// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Processor is an autogenerated mock type for the Processor type
type Processor struct {
	mock.Mock
}

// GetCollectionName provides a mock function with given fields:
func (_m *Processor) GetCollectionName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ProcessAndInsertString provides a mock function with given fields: resource, data
func (_m *Processor) ProcessAndInsertString(resource string, data string) error {
	ret := _m.Called(resource, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(resource, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
