// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"github.com/polyse/database/internal/collection"
	"github.com/polyse/database/internal/web"
)

// Injectors from wire.go:

func initWebApp(ctx context.Context, c *config) (*web.App, func(), error) {
	appConfig, err := initWebAppCfg(c)
	if err != nil {
		return nil, nil, err
	}
	app, cleanup, err := web.NewApp(ctx, appConfig)
	if err != nil {
		return nil, nil, err
	}
	return app, func() {
		cleanup()
	}, nil
}

func initProcessorManager(c *config, collName collection.Name, name collection.BucketName) (*collection.SimpleProcessorManager, func(), error) {
	collectionConfig := initDbConfig(c)
	db, cleanup, err := initConnection(collectionConfig)
	if err != nil {
		return nil, nil, err
	}
	nutsRepository := collection.NewNutRepo(name, db)
	tokenizer := initTokenizer()
	v := initFilters()
	simpleProcessor := collection.NewSimpleProcessor(nutsRepository, collName, tokenizer, v...)
	simpleProcessorManager := collection.NewSimpleProcessorManagerWithProc(simpleProcessor)
	return simpleProcessorManager, func() {
		cleanup()
	}, nil
}
